# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'SwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftProject

  target 'SwiftProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftProjectUITests' do
    # Pods for testing
  end

 pod 'SnapKit', '~> 5.0.0'

end
